#!/usr/bin/env python3
"""en.json へサブエージェント報告分を追記"""
import json

EXTRA = {
    # ---- Task1: app/(main) pages ----
    "2人の好き嫌い率と8項目評価を並べて比較できます。": "Compare two people's like/dislike rates and 8-item ratings side by side.",
    "ID（@から始まる英数字）を直接入力すると確実に追加できます。": "Enter the ID directly (alphanumeric starting with @) to add reliably.",
    "Xでも「{q}」の候補が見つかりませんでした。": "No candidates for “{q}” found on X either.",
    "Xでシェア": "Share on X",
    "XのID（例: ": "X ID (e.g. ",
    "{date} に開幕！": "Opens {date}!",
    "{date} 作成 ・ {n}票": "Created {date} · {n} votes",
    "{n}件": "{n} items",
    "{n}位": "#{n}",
    "{n}点": "{n} pts",
    "{n}票（{pct}%）": "{n} votes ({pct}%)",
    "{votes}票 ・ 評価 {ratings}人": "{votes} votes · {ratings} ratings",
    "※ 誰でも匿名で追加・書き込みができます。誹謗中傷や個人情報の投稿は禁止です。詳しくは": "* Anyone can add and post anonymously. Defamation and personal info are prohibited. See",
    "※ 追加できるのは投稿者以外・1人3個まで・全体で20個まで": "* Only non-creators can add options — 3 per person, 20 total.",
    "※ランキングは書き込みのたびに更新されます。投票は1日1回、評価も毎日書き込めます。": "* Rankings update with every post. Vote once a day; ratings can also be posted daily.",
    "「{option}」に投票しました！": "Voted for “{option}”!",
    "「{q}」が見つかりました": "Found “{q}”",
    "「{q}」をXで検索して追加しています…": "Searching X for “{q}” to add…",
    "【{title}】開催中！期間中の投票数で王者を決めます。毎日投票OK": "【{title}】Live! Total votes during the period crown the champion. Vote daily.",
    "【結果発表】{title}\n王者は {name}（{votes}票）！": "【Results】{title}\nThe champion is {name} ({votes} votes)!",
    "このタグが付いたXユーザーの一覧です（好き率順）。タグはプロフィールから自動判定されます。": "X users with this tag (by like rate). Tags are auto-detected from profiles.",
    "への{type}コメント": " — {type} comments on ",
    "まだ投票トークがありません。最初の1つを作ってみよう！": "No Poll Talks yet. Create the first one!",
    "もう一度試す": "Try again",
    "をご覧ください。": " for details.",
    "キャンセル": "Cancel",
    "タイトル": "Title",
    "テーマは自由。2択・3択以上のアンケートを誰でも作成できて、みんなで投票＆コメントできます。関連する人物を1人以上選んで作成します（アイコンや関連表示に使われます）。": "Any theme. Anyone can create 2-choice or 3+-choice polls — vote and comment together. Pick at least one related person (used for icons and related links).",
    "ページで「好き / 嫌い」に投票＆8項目の評価とコメントを書き込めます": "Vote Like / Dislike and post 8-item ratings and comments on the page",
    "上の検索欄にXのID（例: @maebahesioru2）か名前を入力して検索": "Search by entering an X ID (e.g. @maebahesioru2) or name in the search box above",
    "今日のまとめ（{date}）": "Today's Digest ({date})",
    "今日のツイッタラー世論調査（{date}）\n投票{votes}票・投票した人{voters}人\n急上昇1位は {name}！": "Today's Twitterer Opinion Poll ({date})\n{votes} votes by {voters} people\nToday's top riser: {name}!",
    "今日（JST）: 投票 {votes}・コメント {comments}・評価 {evals}・新規人物 {people}": "Today (JST): {votes} votes · {comments} comments · {evals} ratings · {people} new people",
    "投票": "Vote",
    "投票 {votes}・コメ {comments}・評価 {evals}・新規 {people}": "{votes} votes · {comments} comments · {evals} ratings · {people} new",
    "投票は1人1回まで（変更できません） ・ コメントは誰でも書き込めます": "One vote per person (can't be changed) · Anyone can comment",
    "投票を作成する": "Create a Poll",
    "期間: {period}": "Period: {period}",
    "期間中に集まった「好き／嫌い」投票の合計数でランキングを競います。投票は1日1回・毎日投票OK。": "Rankings compete on the total like/dislike votes during the period. One vote per day — vote daily!",
    "期間限定イベント": "Limited-time event",
    "未登録のユーザーは「X上の候補」から選んで追加（IDを直接入れれば即追加）": "Unregistered users can be added from X suggestions (or enter the ID directly for instant add)",
    "検索結果{extra}：{n}件": "Search results{extra}: {n}",
    "画像URLまたはアップロード（任意）で画像付きに。2択で両方に入れると横並びの「どっち？」形式になります": "Add an image via URL or upload (optional). For 2-choice polls, adding images to both makes a side-by-side “Which?” layout.",
    "評価": "Ratings",
    "追加": "Add",
    "選択肢": "Options",
    "選択肢を追加": "Add option",
    "関連する人物": "Related people",
    "青=正の相関（一緒に高い/低い）、赤=負の相関。1に近いほど連動しています。": "Blue = positive correlation (high/low together), red = negative. Closer to 1 means more linked.",
    "（{n}人）": "({n} people)",
    "（クリックでページを開きます）": "(click to open the page)",
    "（最大5人）": "(max 5 people)",
    "）か名前を入力。名前でヒットしない場合も、X上の候補から選んで追加できます。": ") or a name. If the name doesn't match, you can also pick from X suggestions.",
    # ---- Task2: components ----
    "広告": "Ad",
    "Amazonのアソシエイトとして、当サイトは適格販売により収入を得ています。価格・在庫はAmazonの商品ページでご確認ください。": "As an Amazon Associate, this site earns from qualifying purchases. Prices and availability are subject to change on Amazon.",
    "機能要望・バグ報告・その他、運営への連絡はここにどうぞ。2ch専ブラ（Siki等）からも書き込めます。": "Post feature requests, bug reports, and other messages to the operators here. You can also write from 2ch browsers (e.g. Siki).",
    "まだ書き込みがありません。最初の1件をどうぞ。": "No posts yet. Be the first!",
    "不適切な内容や規約違反のコメントを通報してください。通報内容は運営が確認し、適切な対応を行います。": "Report inappropriate or rule-violating comments. Reports are reviewed by the operators.",
    "{n}/500文字": "{n}/500 chars",
    "好き {n}%": "Like {n}%",
    "嫌い {n}%": "Dislike {n}%",
    "「{q}」の検索結果をすべて見る": "See all results for “{q}”",
    "Xで「{q}」の候補が見つかりました": "Candidates for “{q}” found on X",
    "この中の人ですか？ 選ぶとページを追加して移動します（登録済みならそのまま開きます）": "Is it one of these? Selecting adds the page and takes you there (opens directly if already registered).",
    "登録済み": "Registered",
    "@{handle}・フォロワー{n}": "@{handle} · {n} followers",
    "トレンドランキングをもっと見る": "See more of the trending ranking",
    "画像を外す": "Remove image",
    "ほか {n} 個の選択肢": "{n} more options",
    # ---- 通報理由（REPORT_REASONS） ----
    "殺害・爆破予告": "Threats of killing or bombing",
    "個人情報の晒し": "Posting personal information",
    "自殺ほのめかし": "Suicide hints",
    "誹謗中傷・差別的表現": "Defamation / discriminatory language",
    "なりすまし・嘘の情報": "Impersonation / false information",
    "スパム・宣伝": "Spam / advertising",
    "単に気に入らない": "Simply don't like it",
    "不適切な表現・悪質なネタ": "Inappropriate expression / malicious jokes",
    "自分のコメントを消してほしい": "I want my own comment removed",
    # ---- 人物カテゴリ ----
    "ヒカマー": "Hikamer",
    "配信者": "Streamers",
    "クリエイター": "Creators",
    "企業・サービス": "Companies & Services",
    "芸能人": "Celebrities",
    "政治家": "Politicians",
}

path = "lib/i18n/messages/en.json"
d = json.load(open(path, encoding="utf-8"))
before = len(d)
d.update(EXTRA)
json.dump(d, open(path, "w", encoding="utf-8"), ensure_ascii=False, indent=1, sort_keys=True)
print(f"追加: {len(d)-before} / 合計: {len(d)}")
