#!/usr/bin/env python3
"""en.json 生成（gettext式: 日本語文字列=キー → 英語訳）
プレースホルダは {name} 形式。テンプレ断片（8,9,44-47,51,55,56）は変換側で完全形を組み立てるため含めない。
"""
import json

EN = {
    "{title} - 10/6開幕": "{title} - Opens Oct 6",
    "{a} vs {b} 比較": "{a} vs {b} — Comparison",
    "{a} と {b} の好き嫌い率・8項目評価・票数を並べて比較。": "Compare {a} and {b} side by side — like/dislike rates, 8-item ratings, and vote counts.",
    "{n}点: {c}件": "{n} pts: {c}",
    "{name}の評価・好き嫌い": "{name} — Ratings & Likes/Dislikes",
    "{name}の評価・好き嫌い | {site}": "{name} — Ratings & Likes/Dislikes | {site}",
    "{label}ランキング": "{label} Ranking",
    "10/6(火) 0:00 開幕！期間中の投票で王者を決めよう": "Opens Tue Oct 6, 0:00! Votes during the event decide the champion.",
    "1人目": "First person",
    "1項目以上選んでください": "Select at least one item",
    "24時間": "24 hours",
    "2人のXユーザー（ツイッタラー）を並べて比較できるページです。": "Compare two X users (Twitterers) side by side.",
    "2人を選んでください。": "Select two people.",
    "2人目": "Second person",
    "2択": "2 options",
    "3択以上（固定）": "3+ options (fixed)",
    "3択以上（追加可）": "3+ options (others can add)",
    "8項目の平均点": "Average of the 8 items",
    "8項目の比較": "8-item comparison",
    "8項目の評価": "8-item ratings",
    "8項目評価": "8-item ratings",
    "8項目評価の平均点が低い順。5人以上が評価した人物が対象です。": "Sorted by lowest average of the 8-item ratings. People with 5+ ratings qualify.",
    "8項目評価の平均点が高い順。5人以上が評価した人物が対象です。": "Sorted by highest average of the 8-item ratings. People with 5+ ratings qualify.",
    "8項目評価の相関": "8-item rating correlations",
    ">>{n}\n返信内容を入力...": ">>{n}\nWrite your reply...",
    "@{handle} は現在、別のアカウントが使用されています（ID変更後に解放された可能性）。": "@{handle} is currently used by another account (possibly freed after an ID change).",
    "@IDまたは名前で検索（未登録ユーザーは候補から追加）": "Search by @ID or name (add unregistered users from suggestions)",
    "@IDまたは名前（例: @maebahesioru2 / ツイッタラー）": "@ID or name (e.g. @maebahesioru2)",
    "@ID・名前で検索": "Search by @ID / name",
    "CD・音楽・映像": "CDs, Music & Video",
    "DIY・工具・ガーデン": "DIY, Tools & Garden",
    "No順": "By number",
    "PC・作業環境": "PC & Workspace",
    "URLの投稿はできません": "Posting URLs is not allowed",
    "XのID（@xxx）や名前で検索。未登録のXユーザーも、X上の候補から選ぶかIDを直接入力すればその場でページを作成して、好き嫌い投票・評価を書き込めます。": "Search by X ID (@xxx) or name. Unregistered X users can be added on the spot — pick from X suggestions or enter the ID directly, then vote and rate.",
    "Xの交流相手をグリッドで一覧表示するツール": "A tool to view someone's X interaction partners in a grid",
    "Xユーザーを検索・追加": "Search & add X users",
    "Xユーザーを追加": "Add X user",
    "\n#ツイッタラー世論調査": "\n#ツイッタラー世論調査",
    "sage と入力すると2ch互換板のスレ一覧でこのスレが上がらなくなります": "Entering \"sage\" keeps this thread from bumping on the 2ch-compatible board",
    "sage（2ch互換板のスレ一覧で上がらない投稿）": "sage (won't bump on the 2ch-compatible board)",
    "※投票は1日1回まで": "* One vote per day",
    "← あなた": "← You",
    "← あなたの投票": "← Your vote",
    "「{tag}」の人物一覧": "People tagged “{tag}”",
    "「{tag}」タグが付いたXユーザー（ツイッタラー）の一覧。好き嫌い投票・8項目評価・コメントをチェックできます。": "X users (Twitterers) tagged “{tag}”. Check votes, 8-item ratings, and comments.",
    "「名前#パスワード」で ◆から始まるトリップ（2ch互換の個人証明）が付きます": "Use “name#password” to get a ◆ trip (2ch-compatible ID)",
    "あなたの一票を投じよう": "Cast your vote",
    "おすすめ商品": "Recommended Products",
    "このIDは現在、別のアカウントが使用されています。": "This ID is currently used by another account.",
    "このXアカウントは現在確認できません（凍結・削除・ID変更など）。": "This X account can't be confirmed right now (suspended, deleted, renamed, etc.).",
    "この評価を送信する（{answered}/8項目）": "Submit this rating ({answered}/8 items)",
    "すべて": "All",
    "その他": "Other",
    "まだコメントがありません": "No comments yet",
    "まだコメントがありません。最初のコメントを書いてみよう！": "No comments yet. Be the first to comment!",
    "まだデータがありません": "No data yet",
    "まだデータがありません（5人以上の評価が必要）": "No data yet (needs 5+ ratings)",
    "まだ投票がありません": "No votes yet",
    "まだ票がありません": "No votes yet",
    "みんなで作るアンケート「投票トーク」。誰でも作成・投票・コメントできます。": "“Poll Talk” — polls made by everyone. Anyone can create, vote, and comment.",
    "もう1人選ぶと比較が表示されます。": "Pick one more person to see the comparison.",
    "アップロード": "Upload",
    "アップロードに失敗しました": "Upload failed",
    "エラーが発生しました。": "An error occurred.",
    "エラーが発生しました。ページをリロードして再度お試しください。": "An error occurred. Reload the page and try again.",
    "カテゴリ": "Category",
    "カテゴリ別": "By category",
    "カー・バイク": "Cars & Bikes",
    "ガジェット・家電": "Gadgets & Appliances",
    "ゲーム": "Games",
    "コスメ・美容": "Cosmetics & Beauty",
    "コピーに失敗しました": "Copy failed",
    "コピー完了": "Copied",
    "コメント": "Comments",
    "コメントはありません": "No comments",
    "コメントは全角{n}文字（半角{m}文字）以内です": "Comments must be within {n} full-width ({m} half-width) characters",
    "コメントは全角140文字（半角280文字）以内です": "Comments must be within 140 full-width (280 half-width) characters",
    "コメントを入力...（全角140文字まで）": "Write a comment... (up to 140 full-width chars)",
    "コメントを入力してください": "Please enter a comment",
    "コメントを投稿": "Post comment",
    "コメントを投稿しました": "Comment posted",
    "コメントを通報": "Report comment",
    "コメントを非表示にしました": "Comment hidden",
    "スコア分布": "Score distribution",
    "スパム行為、荒らし行為": "Spam or vandalism",
    "スポーツ・アウトドア": "Sports & Outdoors",
    "タイトルを入力してください": "Please enter a title",
    "タグ": "Tags",
    "タグ別（2人以上・上位20）": "By tag (2+ people, top 20)",
    "タップして投票": "Tap to vote",
    "ダークモードに切り替え": "Switch to dark mode",
    "ツイッタラー世論調査": "Twitterer Opinion Poll",
    "ツイッタラー世論調査の統計。カテゴリ別・タグ別の傾向、8項目評価の相関とスコア分布を公開しています。": "Stats for the Twitterer Opinion Poll — category and tag trends, 8-item rating correlations, and score distributions.",
    "ツイッタラー世論調査への機能要望・バグ報告・その他の連絡用スレッドです。": "Thread for feature requests, bug reports, and other contact regarding the site.",
    "ツイッタラー比較": "Twitterer comparison",
    "テーマ切替": "Toggle theme",
    "トレンド": "Trending",
    "ファッション": "Fashion",
    "ベビー・キッズ": "Baby & Kids",
    "ペット": "Pets",
    "ページを見る →": "View page →",
    "ホビー・おもちゃ": "Hobbies & Toys",
    "メニュー": "Menu",
    "メール（sageでageない）": "Email (use sage to not bump)",
    "ユーザーは、本サイトの利用にあたり、以下の行為をしてはなりません。": "Users must not engage in the following when using this site.",
    "ライトモードに切り替え": "Switch to light mode",
    "ランキング": "Rankings",
    "リンクをコピー": "Copy link",
    "ルール": "Rules",
    "・": "•",
    "・ {n}フォロワー": "• {n} followers",
    "不人気": "Unpopular",
    "不正アクセス、またはこれを試みる行為": "Unauthorized access or attempts thereof",
    "並び:": "Sort:",
    "並び替え": "Sort",
    "人数": "People",
    "人物が見つかりません": "Person not found",
    "人物一覧": "People",
    "今日のまとめ": "Today's Digest",
    "今日のまとめ - ツイッタラー世論調査": "Today's Digest - Twitterer Opinion Poll",
    "今日のツイッタラー世論調査（{date}）\n投票{votes}票・投票した人{voters}人\n急上昇1位は {name}": "Today's Twitterer Opinion Poll ({date})\n{votes} votes by {voters} people\nToday's top riser: {name}",
    "今日の投票": "Today's votes",
    "今日の投票数・24時間の急上昇ランキング・新しく追加されたXユーザー・新着コメントをまとめてチェック。": "Today's vote count, 24-hour trending, newly added X users, and latest comments — all in one place.",
    "今日の数字・急上昇・新着をまとめてチェック。": "Check today's numbers, risers, and new arrivals at a glance.",
    "今日は既に投票済みです。\n\n投票は1日1回可能です。明日また投票してください。": "You've already voted today.\n\nYou can vote once per day. Come back tomorrow!",
    "今日追加されたXユーザー": "X users added today",
    "今週の急上昇": "This week's risers",
    "他のタグ": "Other tags",
    "他のユーザーまたは第三者の権利を侵害する行為": "Infringing the rights of other users or third parties",
    "他の人も選択肢を追加できます（最大20個・1人3個まで）": "Others can add options too (max 20 total, 3 per person)",
    "低評価": "Low ratings",
    "低評価ワースト5": "Worst 5 by score",
    "作成には利用規約への同意が必要です。ページを再読み込みしてください。": "You must agree to the Terms to create. Please reload the page.",
    "作成に失敗しました": "Failed to create",
    "作成中...": "Creating...",
    "例: 一番好きなツイッタラーは？": "e.g. Who's your favorite Twitterer?",
    "個人情報（住所・電話番号等）を晒す行為": "Doxxing (posting addresses, phone numbers, etc.)",
    "健康・ドラッグ": "Health & Drugs",
    "充電・モバイル": "Charging & Mobile",
    "具体的な内容や補足情報があれば入力してください": "Enter details or additional info if any",
    "処理中...": "Processing...",
    "利用規約": "Terms of Use",
    "利用規約への同意": "Agree to Terms",
    "削除": "Delete",
    "匿名": "Anonymous",
    "各項目の評価（1〜5）の割合。": "Distribution of ratings (1–5) per item.",
    "同意する": "Agree",
    "名前・@IDで検索": "Search by name / @ID",
    "名前・IDで検索": "Search by name / ID",
    "名前順": "By name",
    "名前（任意・#でトリップ）": "Name (optional; # for trip)",
    "名無しさん": "Anonymous",
    "好き": "Like",
    "好き / 嫌い": "Like / Dislike",
    "好き派": "Likers",
    "好き率が高い人": "Most liked",
    "好き率が高い順。1票以上集めた人物が対象です。": "Sorted by like rate. People with 1+ votes qualify.",
    "好き率順": "By like rate",
    "好感度": "Favorability",
    "嫌い": "Dislike",
    "嫌い派": "Dislikers",
    "嫌い率が高い人": "Most disliked",
    "嫌い率が高い順。1票以上集めた人物が対象です。": "Sorted by dislike rate. People with 1+ votes qualify.",
    "寝具・タオル": "Bedding & Towels",
    "平均スコア": "Avg. score",
    "平均好き率": "Avg. like rate",
    "広告を閉じる": "Close ad",
    "引き直す": "Reroll",
    "投票した人": "Voters",
    "投票には利用規約への同意が必要です。ページを再読み込みしてください。": "You must agree to the Terms to vote. Please reload the page.",
    "投票に失敗しました": "Vote failed",
    "投票に失敗しました。もう一度お試しください。": "Vote failed. Please try again.",
    "投票は1人につき1日1回。毎日投票できます（毎日来るほど推しが有利）": "One vote per person per day. Vote daily — the more you come, the better for your favorite.",
    "投票トーク": "Poll Talk",
    "投票トークを作成": "Create a Poll Talk",
    "投票形式": "Poll type",
    "投票数順": "By votes",
    "投票結果": "Results",
    "投稿": "Post",
    "投稿には利用規約への同意が必要です。ページを再読み込みしてください。": "You must agree to the Terms to post. Please reload the page.",
    "投稿に失敗しました": "Post failed",
    "投稿中...": "Posting...",
    "文具・オフィス": "Stationery & Office",
    "新しい選択肢": "New option",
    "新しく追加": "Recently added",
    "新しく追加された人物のページも対象です（検索から誰でも追加できます）": "Newly added people count too (anyone can add via search)",
    "新着コメント": "Latest comments",
    "新着順": "Newest",
    "既に投票済みです": "Already voted",
    "日別のカウント（JST）。棒の長さは各指標の最大値比。": "Daily counts (JST). Bar length is relative to each metric's max.",
    "書き込みには利用規約への同意が必要です。ページを再読み込みしてください。": "You must agree to the Terms to write. Please reload the page.",
    "書き込みに失敗しました": "Failed to write",
    "書き込む": "Write",
    "最終結果": "Final results",
    "最近追加されたXユーザー": "Recently added X users",
    "期間中に集まった「好き」「嫌い」の投票数の合計で競います": "Compete on the total number of like + dislike votes during the period",
    "期間中の投票数で王者を決める期間限定イベント。毎日1票、推しに投票しよう。": "A limited-time event — total votes during the period crown the champion. One vote a day to support your favorite.",
    "未登録だったので追加しました": "Wasn't registered, so we added them",
    "未登録のユーザーはその場でページを作成します": "Unregistered users get a page created on the spot",
    "本": "Books",
    "本サイトの運営を妨害する行為": "Interfering with the operation of this site",
    "本文は全角{n}文字（半角{m}文字）以内です": "Text must be within {n} full-width ({m} half-width) characters",
    "本文を入力してください": "Please enter text",
    "検索結果": "Search results",
    "法令または公序良俗に違反する行為": "Violating laws or public order and morals",
    "犯罪行為に関連する行為": "Acts related to criminal activity",
    "生活・キッチン": "Living & Kitchen",
    "生活・収納・家具": "Storage & Furniture",
    "生活・雑貨": "Daily Goods",
    "産業・研究": "Industrial & Research",
    "画像URL（任意・https://…）またはここにアップロード": "Image URL (optional, https://…) or upload here",
    "登録されている全人物の一覧。タグ・カテゴリ・並び替え・検索で気になる人を探せます。": "All registered people. Find anyone by tag, category, sort, or search.",
    "登録人物": "Registered people",
    "登録済みでした": "Already registered",
    "直近7日の推移": "Last 7 days",
    "票数": "Votes",
    "第1条（適用）": "Article 1 (Scope)",
    "第2条（禁止事項）": "Article 2 (Prohibited Acts)",
    "第3条（投稿コンテンツ）": "Article 3 (Posted Content)",
    "第4条（コンテンツの削除）": "Article 4 (Content Removal)",
    "第5条（免責事項）": "Article 5 (Disclaimer)",
    "第6条（利用制限）": "Article 6 (Usage Restrictions)",
    "第7条（発信者情報の開示請求への対応）": "Article 7 (Handling of Disclosure Requests)",
    "第8条（変更）": "Article 8 (Changes)",
    "管理スレ": "Admin Thread",
    "管理スレ（要望・バグ報告）": "Admin thread (requests & bug reports)",
    "結果は期間終了後にこのページで発表します": "Results will be announced on this page after the period ends",
    "統計": "Stats",
    "総合": "Overall",
    "総合評価": "Overall rating",
    "総合評価トップ5": "Top 5 by overall rating",
    "総合評価（8項目の平均）": "Overall rating (avg. of 8 items)",
    "総投票 {n}": "Total votes: {n}",
    "総投票数": "Total votes",
    "自動化ツール等を使用した不正な投稿": "Fraudulent posts using automation tools",
    "補足説明があれば": "Add notes if any",
    "要望・バグ報告・その他を入力...（全角140文字まで）": "Enter requests, bug reports, etc. (up to 140 full-width chars)",
    "評価には利用規約への同意が必要です。ページを再読み込みしてください。": "You must agree to the Terms to rate. Please reload the page.",
    "評価の送信に失敗しました": "Failed to submit rating",
    "詳細・備考（任意）": "Details / notes (optional)",
    "説明（任意）": "Description (optional)",
    "読み込み中…": "Loading…",
    "誹謗中傷、嫌がらせ、脅迫等の行為": "Defamation, harassment, threats, etc.",
    "返信には利用規約への同意が必要です": "You must agree to the Terms to reply",
    "返信に失敗しました": "Reply failed",
    "返信を投稿": "Post reply",
    "追加できませんでした": "Could not add",
    "追加に失敗しました": "Failed to add",
    "追加のしかた": "How to add",
    "送信中": "Sending",
    "送信中...": "Sending...",
    "途中経過": "Standings",
    "通信エラーが発生しました": "A network error occurred",
    "通報": "Report",
    "通報する": "Submit report",
    "通報に失敗しました": "Report failed",
    "通報を受け付けました。\n\nご協力ありがとうございます。": "Report received.\n\nThank you for your help.",
    "通報理由を選択してください": "Please select a reason",
    "過去24時間の投票数ランキング。今日動いてる人をチェック。": "Vote ranking for the last 24 hours. See who's active today.",
    "過去7日間の投票数ランキング。今話題の人をチェック。": "Vote ranking for the last 7 days. See who's hot right now.",
    "選択肢 {n}": "Option {n}",
    "選択肢2つ。他の人は追加できません": "2 options. Others can't add more.",
    "選択肢3つ以上。他の人は追加できません": "3+ options. Others can't add more.",
    "選択肢の追加には利用規約への同意が必要です": "You must agree to the Terms to add options",
    "選択肢を{min}つ以上入力してください": "Enter at least {min} options",
    "選択肢を追加する": "Add an option",
    "閉じる": "Close",
    "閉幕！最終結果はこちら": "Closed! Final results here",
    "閉幕！結果をチェック": "Closed! Check the results",
    "開催中！10/12(月)まで — 毎日投票で推しを押し上げよう": "Live until Mon Oct 12 — vote daily to boost your favorite",
    "開催中！残り{n}日": "Live! {n} days left",
    "関連:": "Related:",
    "関連する人物を1人以上選んでください": "Select at least one related person",
    "防災・生活": "Emergency & Living",
    "防犯・カメラ": "Security & Cameras",
    "集まったデータの傾向をまとめています。": "Trends from the data collected so far.",
    "非表示": "Hide",
    "音・配信・DTM": "Audio, Streaming & DTM",
    "食品・飲料": "Food & Beverages",
    "（{page}/{total}ページ）": "({page}/{total} pages)",
    "（ほか）": "(more)",
}

import os
os.makedirs("lib/i18n/messages", exist_ok=True)
with open("lib/i18n/messages/en.json", "w", encoding="utf-8") as f:
    json.dump(EN, f, ensure_ascii=False, indent=1, sort_keys=True)
print(f"en.json 書き込み: {len(EN)} エントリ")
